# Generated by Django 4.2.7 on 2023-12-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=11)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('Male', True), ('Female', False)])),
                ('telephone', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=3)),
                ('chronic_diseases', models.CharField(max_length=50)),
                ('medical_allergy', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=30)),
                ('address_number', models.CharField(max_length=5)),
            ],
        ),
    ]
