# Generated by Django 4.2.7 on 2023-12-28 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_patientpost_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goal_of_appointment', models.CharField(max_length=512)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('reasons_for_admission', models.CharField(max_length=255)),
                ('diagnostic_tests', models.CharField(max_length=255)),
                ('diagnosis', models.CharField(max_length=50)),
                ('treatment_plan', models.CharField(max_length=512)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('medical_procedures', models.CharField(max_length=512)),
                ('additional_info', models.CharField(max_length=512)),
                ('diagnosis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.diagnosis')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('pesel', models.CharField(max_length=11)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField()),
                ('telephone', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=3)),
                ('chronic_diseases', models.CharField(max_length=50)),
                ('medical_allergy', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=30)),
                ('address_number', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientPost',
        ),
        migrations.AddField(
            model_name='unit',
            name='ward_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ward'),
        ),
        migrations.AddField(
            model_name='hospitalstay',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
        migrations.AddField(
            model_name='hospitalstay',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unit'),
        ),
        migrations.AddField(
            model_name='hospitalstay',
            name='ward_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ward'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
    ]
