# Generated by Django 4.2.7 on 2023-12-28 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment_diagnosis_hospitalstay_patient_unit_ward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_number',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_diseases',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 28, 19, 57, 21, 780897, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_allergy',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pesel',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
