# Generated by Django 4.2.7 on 2024-01-01 00:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('number_of_beds', models.CharField(max_length=5)),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branch')),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='ward_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pesel',
            new_name='id_number',
        ),
        migrations.RemoveField(
            model_name='hospitalstay',
            name='ward_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='satus',
            field=models.CharField(default='discharged'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 0, 58, 53, 225156, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='admission_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 0, 58, 53, 226155, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hospitalstay',
            name='admission_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 0, 58, 53, 227168, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 0, 58, 53, 224156, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(default=True),
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.AddField(
            model_name='branch',
            name='hospital_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='main.diagnosiscode'),
        ),
        migrations.AlterField(
            model_name='hospitalstay',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
