# Generated by Django 4.2.7 on 2024-01-01 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='ward_id',
            new_name='branch_id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 1, 14, 18, 559276, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='admission_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 1, 14, 18, 560275, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hospitalstay',
            name='admission_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 1, 14, 18, 561274, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 1, 14, 18, 559276, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
