# Generated by Django 4.2.7 on 2024-01-02 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='satus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 16, 3, 21, 348600, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='admission_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 2, 16, 3, 21, 348600, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hospitalstay',
            name='admission_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 2, 16, 3, 21, 350599, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 2, 16, 3, 21, 347601, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
