# Generated by Django 4.2.7 on 2024-01-03 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_satus_patient_status_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='hospital_id',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='hospitalstay',
            old_name='diagnosis_id',
            new_name='diagnosis',
        ),
        migrations.RenameField(
            model_name='hospitalstay',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='hospitalstay',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='hospitalstay',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 15, 42, 29, 861140, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='admission_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 3, 15, 42, 29, 862159, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hospitalstay',
            name='admission_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 3, 15, 42, 29, 863158, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 3, 15, 42, 29, 861140, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
